### ISSUE TITLE
Bring up k8s cluster(c3) using Rancher on centos7

### ISSUE THREAD

**Issue by prabhatkumarthakur** [mayadata-io/oep-e2e#548]
I need to bring up c3 cluster using Rancher.

**Comment by prabhatkumarthakur** [comment]
Steps followed by Harsh to bring up rancher cluster.
```
********** Setting up Rancher deployer VM *********

# Installing Docker

{
yum check-update
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker -y
systemctl start docker
systemctl enable docker
}

# Run Rancher container

docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 rancher/rancher:latest


************** Setting up cluster VM's ***********

# Installing Docker

{
yum check-update
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker -y
systemctl start docker
systemctl enable docker
}

# Installing ISCSI initiator

{
    yum install iscsi-initiator-utils -y
    systemctl enable iscsid
    systemctl start iscsid
    modprobe iscsi_tcp
}


# Disable firewalld on master

{
firewall-cmd --state
systemctl stop firewalld
systemctl disable firewalld
systemctl mask --now firewalld
}

{
systemctl unmask --now firewalld
systemctl enable firewalld
systemctl start firewalld
firewall-cmd --state
}



 RKE Template ---------------------------------------------------------


# 
# Cluster Config
# 
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: rancher2
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: v1.15.11-rancher1-1
  monitoring:
    provider: metrics-server
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
# 
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: weave
    weave_network_provider:
      password: 'Y)YJ#KfSj[82[JqJ'
# 
    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
      kubelet:
      extra_binds:                                              
      - "/etc/iscsi:/etc/iscsi"                                 
      - "/sbin/iscsiadm:/sbin/iscsiadm"                         
      - "/var/lib/iscsi:/var/lib/iscsi"                         
      - "/lib/modules"
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
# 
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: 5000
        heartbeat-interval: 500
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
  ssh_agent_auth: false
windows_prefered_cluster: false
```
