### ISSUE TITLE
After openebs cleanup when we are trying to install openebs again then it is failling.

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#553]
- In our pipeline we run  multiple test cases for openebs installation in sequence.
- So after installing openebs we also need to clear it and reinstall it.
- When I am doing this sometimes jobs are failing in pipeline.
Post check after deleting the openebs: 
- Checking openebs entry that should be in removed state.
```
- name: Check openebs is removed or not from cluster
  uri:
    url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses"
    method: GET
    url_username: "{{ username.stdout }}"
    url_password: "{{ password.stdout }}" 
    return_content: yes
    force_basic_auth: yes
    body_format: json
  register: openebs_details
  until: "openebs_details.json.data[0].state == 'removed'"
  retries: 30
  delay: 10
```

- Looking for openebs components
  ```- name: Verify openebs is removed or not
  uri:
    url: "{{ director_url }}/v3/clusters/{{ cluster_id }}"
    method: GET
    url_username: "{{ username.stdout }}"
    url_password: "{{ password.stdout }}"
    return_content: yes
    force_basic_auth: yes
    body_format: json
  register: openebs_components_details



#### Pipeline details: https://gitlab.mayadata.io/oep/oep-e2e-aws/-/jobs/115431

#### Logs: 
```
TASK [Installing openebs on the cluster] ***************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "connection": "close", "content": "{\"id\":\"ad695c87-1952-4f67-b88d-9e29b681fc0d\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":400,\"code\":\"InvalidBodyContent\",\"message\":\"InvalidBodyContent\",\"detail\":null,\"baseType\":\"error\"}", "content_length": "189", "content_type": "application/json; charset=utf-8", "date": "Thu, 14 May 2020 06:49:40 GMT", "elapsed": 0, "expires": "Thu, 01 Jan 1970 00:00:00 GMT", "json": {"actions": {}, "baseType": "error", "code": "InvalidBodyContent", "detail": null, "id": "ad695c87-1952-4f67-b88d-9e29b681fc0d", "links": {}, "message": "InvalidBodyContent", "status": 400, "type": "error"}, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "set_cookie": "PL=DirectorOnline;Path=/", "status": 400, "url": "http://34.219.152.125/v3/groups/1a20/openebses/1o2?action=openebsinstall", "x_api_schemas": "http://34.219.152.125/v3/groups/1a20/schemas"}
