### ISSUE TITLE
bug: use mayadata.io images in gitlab stages

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/oep-e2e#576]
https://github.com/mayadata-io/oep-e2e-rancher/blob/oep-release/.gitlab-ci.yml
```yaml
DEPLOY-CSI-PROVISIONER:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-INSTALL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/deploy-csi-provisioner
    - ./stages/openebs-install/deploy-csi-provisioner
```
use mayadata.io images instead of above image.
